apiVersion: apps/v1
kind: Deployment
metadata:
  name: csti-api
  labels:
    app: csti-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csti-api
  template:
    metadata:
      labels:
        app: csti-api
    spec:
      containers:
        - name: csti-api
          image: 228159236951.dkr.ecr.sa-east-1.amazonaws.com/csti-tokenizacion:latest
          ports:
            - containerPort: 8000
        - name: csto-redis
          image: redis:6.2-alpine
          ports:
            - containerPort: 6379
